Repository dklog-team/dklog, pull requests merged in 2023-05, with the labels that each got.

#22 Feature/dklog 19
  src/main/java/kr/dklog/common/util/NcpSmsUtil.java
  src/main/java/kr/dklog/common/util/PagingUtil.java
  src/main/java/kr/dklog/controller/HomeController.java
  src/main/java/kr/dklog/dto/common/RequestListDto.java
  src/main/java/kr/dklog/dto/common/ResponseListDto.java
  src/main/java/kr/dklog/dto/response/ResponsePostListDto.java
  src/main/java/kr/dklog/mapper/PostMapper.java
  src/main/java/kr/dklog/service/PostService.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/templates/index.html
Labels: feature

#21 Feature/dklog 9
  src/main/java/kr/dklog/controller/ImageController.java
  src/main/java/kr/dklog/dto/ImageDto.java
  src/main/java/kr/dklog/dto/request/RequestUploadImageDto.java
  src/main/java/kr/dklog/dto/response/ResponseUploadResultDto.java
  src/main/java/kr/dklog/mapper/ImageMapper.java
  src/main/java/kr/dklog/service/FileUploadService.java
  src/main/resources/mapper/ImageMapper.xml
Labels: feature

#28 Feature/dklog 26
  src/main/java/kr/dklog/dto/common/OAuthAttributesDto.java
  src/main/java/kr/dklog/service/CustomOAuth2MemberService.java
  src/main/resources/mapper/MemberMapper.xml
Labels: fix

#29 Feature/dklog 24
  src/main/java/kr/dklog/controller/PostController.java
  src/main/java/kr/dklog/dto/request/RequestPostDto.java
  src/main/java/kr/dklog/mapper/PostMapper.java
  src/main/java/kr/dklog/service/PostService.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/templates/view/error/post-upload-fail.html
  src/main/resources/templates/view/write.html
Labels: feature

#30 Feature/dklog 23
  src/main/java/kr/dklog/controller/CommentController.java
  src/main/java/kr/dklog/dto/CommentDto.java
  src/main/java/kr/dklog/dto/response/ResponseCommentDto.java
  src/main/java/kr/dklog/mapper/CommentMapper.java
  src/main/java/kr/dklog/service/CommentService.java
  src/main/resources/mapper/CommentMapper.xml
  src/main/resources/templates/view/comment.html
Labels: feature

#34 Feature/dklog 33
  src/main/java/kr/dklog/controller/PostController.java
  src/main/resources/templates/view/write.html
Labels: fix

#35 Feature/dklog 23
  src/main/java/kr/dklog/controller/CommentController.java
  src/main/java/kr/dklog/dto/CommentDto.java
  src/main/java/kr/dklog/dto/response/ResponseCommentDto.java
  src/main/java/kr/dklog/mapper/CommentMapper.java
  src/main/java/kr/dklog/service/CommentService.java
  src/main/resources/mapper/CommentMapper.xml
  src/main/resources/templates/view/comment.html
Labels: feature

#38 Feature/dklog 37
  src/main/java/kr/dklog/controller/PostController.java
  src/main/java/kr/dklog/dto/request/RequestUpdatePostDto.java
  src/main/java/kr/dklog/mapper/PostMapper.java
  src/main/java/kr/dklog/service/PostService.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/static/images/post-delete-icon.png
  src/main/resources/static/images/post-edit-icon.png
  src/main/resources/templates/view/post-detail.html
  src/main/resources/templates/view/write.html
Labels: feature

#39 Feature/dklog 36
  src/main/java/kr/dklog/controller/CommentController.java
  src/main/java/kr/dklog/dto/CommentDto.java
  src/main/java/kr/dklog/dto/response/ResponseCommentDto.java
  src/main/java/kr/dklog/mapper/CommentMapper.java
  src/main/java/kr/dklog/mapper/MemberMapper.java
  src/main/java/kr/dklog/service/CommentService.java
  src/main/resources/mapper/CommentMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/templates/view/comment.html
Labels: feature

#41 Feature/dklog 32
  src/main/java/kr/dklog/dto/common/RequestListDto.java
  src/main/java/kr/dklog/mapper/PostMapper.java
  src/main/java/kr/dklog/service/PostService.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/templates/fragments/header.html
Labels: feature

#45 Feature/dklog 31
  src/main/java/kr/dklog/controller/ImageController.java
  src/main/java/kr/dklog/dto/response/ResponseUploadResultDto.java
  src/main/java/kr/dklog/service/FileUploadService.java
  src/main/resources/mapper/ImageMapper.xml
  src/main/resources/templates/view/write.html
Labels: feature

#48 Bugfix/dklog 43
  src/main/resources/templates/view/write.html
Labels: fix

#50 Bugfix/dklog 49
  src/main/java/kr/dklog/service/PostService.java
Labels: fix

#52 Bugfix/dklog 51
  src/main/java/kr/dklog/controller/PostController.java
Labels: fix

#53 Feature/dklog 46
  src/main/java/kr/dklog/controller/PostController.java
  src/main/java/kr/dklog/mapper/PostMapper.java
  src/main/java/kr/dklog/service/PostService.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/templates/view/post-detail.html
Labels: feature

#54 Feature/dklog 44
  src/main/resources/static/css/style.css
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/view/write.html
Labels: feature

#57 Bugfix/dklog 55
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/view/write.html
Labels: fix

#58 Feature/dklog 56
  src/main/resources/templates/fragments/header.html
Labels: feature

#59 feat: 댓글 수정 기능 구현 중간 점검
  src/main/java/kr/dklog/controller/CommentController.java
  src/main/java/kr/dklog/dto/response/ResponseCommentDto.java
  src/main/java/kr/dklog/mapper/CommentMapper.java
  src/main/java/kr/dklog/service/CommentService.java
  src/main/resources/mapper/CommentMapper.xml
  src/main/resources/templates/view/comment.html
Labels: feature

#62 Bugfix/dklog 61
  src/main/resources/templates/view/write.html
Labels: fix

#67 Feature/dklog 66
  src/main/resources/templates/view/post-detail.html
Labels: feature

#68 Bugfix/dklog 65
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
Labels: fix

#72 Bugfix/dklog 71
  src/main/resources/templates/view/post-detail.html
Labels: fix

#74 Feature/dklog 73
  src/main/java/kr/dklog/common/exception/AlreadyAuthStudentException.java
  src/main/java/kr/dklog/dto/StudentDto.java
  src/main/java/kr/dklog/service/AuthCodeService.java
  src/main/resources/mapper/StudentMapper.xml
Labels: feature

#76 Feature/dklog 75
  src/main/java/kr/dklog/controller/PostController.java
  src/main/java/kr/dklog/mapper/CommentMapper.java
  src/main/java/kr/dklog/service/CommentService.java
  src/main/resources/mapper/CommentMapper.xml
  src/main/resources/static/js/common/comment-util.js
  src/main/resources/templates/fragments/comment.html
Labels: feature

#79 Feature/dklog 77
  src/main/java/kr/dklog/service/PostService.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/fragments/comment.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/index.html
  src/main/resources/templates/view/post-detail.html
  src/main/resources/templates/view/write.html
Labels: feature

#81 Bugfix/dklog 80
  build.gradle
  src/main/java/kr/dklog/controller/ImageController.java
  src/main/resources/templates/view/write.html
Labels: fix

#82 Bugfix/dklog 80
  build.gradle
  src/main/java/kr/dklog/controller/ImageController.java
Labels: fix

#84 Bugfix/dklog 83
  src/main/resources/static/js/common/comment-util.js
  src/main/resources/templates/fragments/comment.html
  src/main/resources/templates/index.html
  src/main/resources/templates/view/post-detail.html
Labels: fix

#86 Feature/dklog 85
  src/main/java/kr/dklog/controller/TutorialController.java
  src/main/resources/static/js/markdown-example.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/view/write-tutorial.html
Labels: feature

#89 Feature/dklog 87
  src/main/resources/templates/index.html
Labels: fix

#91 Feature/dklog 90
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/top-scroll.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layouts/comment-layout.html
  src/main/resources/templates/layouts/default-layout.html
Labels: feature

#93 Bugfix/dklog 92
  build.gradle
  src/main/java/kr/dklog/controller/ImageController.java
  src/main/java/kr/dklog/service/FileUploadService.java
  src/main/resources/static/js/api/core/request.js
  src/main/resources/static/js/common/comment-util.js
  src/main/resources/templates/fragments/comment.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/view/post-detail.html
  src/main/resources/templates/view/student-auth.html
  src/main/resources/templates/view/write-tutorial.html
  src/main/resources/templates/view/write.html
Labels: fix

#95 Bugfix/dklog 94
  build.gradle
  src/main/java/kr/dklog/service/AuthCodeService.java
  src/main/resources/templates/view/write.html
Labels: bug

#97 Feature/dklog 96
  build.gradle
  src/main/resources/static/images/favicon.ico
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/view/error/login-fail.html
  src/main/resources/templates/view/error/post-upload-fail.html
  src/main/resources/templates/view/write-tutorial.html
  src/main/resources/templates/view/write.html
Labels: feature

#99 Feature/dklog 98
  build.gradle
  src/main/java/kr/dklog/common/exception/ExceptionController.java
  src/main/java/kr/dklog/controller/CommentController.java
  src/main/java/kr/dklog/dto/common/ResponseErrorDto.java
  src/main/java/kr/dklog/dto/request/RequestAddCommentDto.java
  src/main/java/kr/dklog/dto/request/RequestDeleteCommentDto.java
  src/main/java/kr/dklog/dto/request/RequestUpdateCommentDto.java
  src/main/java/kr/dklog/dto/response/ResponseCommentDto.java
  src/main/java/kr/dklog/service/CommentService.java
Labels: feature

#104 Feature/dklog 103
  src/main/java/kr/dklog/controller/PostController.java
  src/main/java/kr/dklog/dto/PostDto.java
  src/main/java/kr/dklog/dto/response/PreviewPostDto.java
  src/main/java/kr/dklog/dto/response/ResponsePostDto.java
  src/main/java/kr/dklog/mapper/PostMapper.java
  src/main/java/kr/dklog/service/PostService.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/static/js/markdown-example.js
  src/main/resources/templates/index.html
  src/main/resources/templates/view/post-detail.html
Labels: feature

#106 Feature/dklog 105
  src/main/java/kr/dklog/common/interceptor/VisitorCountInterceptor.java
  src/main/java/kr/dklog/configuration/MvcConfiguration.java
  src/main/java/kr/dklog/controller/CommentController.java
  src/main/java/kr/dklog/dto/VisitorDto.java
  src/main/java/kr/dklog/mapper/VisitorMapper.java
  src/main/java/kr/dklog/service/VisitorService.java
  src/main/resources/mapper/VisitorMapper.xml
Labels: feature

#108 Develop
  src/main/java/kr/dklog/common/interceptor/VisitorCountInterceptor.java
  src/main/java/kr/dklog/configuration/MvcConfiguration.java
  src/main/java/kr/dklog/controller/CommentController.java
  src/main/java/kr/dklog/controller/PostController.java
  src/main/java/kr/dklog/dto/PostDto.java
  src/main/java/kr/dklog/dto/VisitorDto.java
  src/main/java/kr/dklog/dto/response/PreviewPostDto.java
  src/main/java/kr/dklog/dto/response/ResponsePostDto.java
  src/main/java/kr/dklog/mapper/PostMapper.java
  src/main/java/kr/dklog/mapper/VisitorMapper.java
  src/main/java/kr/dklog/service/PostService.java
  src/main/java/kr/dklog/service/VisitorService.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/mapper/VisitorMapper.xml
  src/main/resources/static/js/markdown-example.js
  src/main/resources/templates/index.html
  src/main/resources/templates/view/post-detail.html
Labels: feature

#110 feat: 프로젝트 기능 개선
  src/main/java/kr/dklog/common/interceptor/VisitorCountInterceptor.java
  src/main/java/kr/dklog/dto/VisitorDto.java
  src/main/java/kr/dklog/dto/request/RequestPostDto.java
  src/main/java/kr/dklog/dto/request/RequestUpdatePostDto.java
  src/main/java/kr/dklog/service/PostService.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/mapper/VisitorMapper.xml
Labels: feature
